"""Preservation tests for the module-transition-question-duplication bugfix.

These tests encode design **Property 3** ("Preservation — All Other Completion
and Question Behavior Unchanged"). Unlike the bug-condition exploration tests,
these are AUTHORED TO PASS on the current (unfixed) steering/hook files: they
establish the frozen baseline the fix must NOT disturb.

Observation-first methodology
-----------------------------
The frozen SHA-256 values below were computed from the CURRENT (unfixed) files
and embedded here as the expected baseline. Because the fix has not happened
yet, every check trivially holds today; after the fix these same frozen values
detect any unintended drift in a file (or file region) the fix is not supposed
to touch.

Scope of the fix (the ONLY things allowed to change)
----------------------------------------------------
Editable steering files:
    * ``module-completion-next-steps.md``
    * ``module-completion.md``
    * ``module-transitions.md``
Editable hook:
    * ``ask-bootcamper.json`` (Phase 1 / Phase 1.5 prompt wording only)
Regenerated by the re-sync scripts (therefore excluded from byte-identity):
    * ``hook-registry-critical.md`` (mirrors the full ``ask-bootcamper`` prompt)
    * ``steering-index.yaml`` (token counts refreshed — not a ``.md`` file, so it
      is naturally outside the ``*.md`` byte-identity scan) and the hook-registry
      lockfile.

Everything else under ``senzing-bootcamp/steering/`` must remain byte-identical,
and the edited files must retain their non-target anchors (completion step
order, Shared Boundary-Detection Trigger rules, the ⛔ Immediate Execution rule,
the next-step options set, the Confirmation Response Requirements table, and the
ascending-numeric-order sequencing rule). The ``ask-bootcamper`` Stop trigger,
``agent`` action type, and Phases 0/2/3/4 must be unchanged. The
``config/.question_pending`` lifecycle rules (write-policy-gate validation,
treat-as-answer, delete-and-process) must remain referenced and unchanged.

Feature: module-transition-question-duplication

**Validates: Requirements 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7**
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

from hypothesis import given
from hypothesis import strategies as st

# ---------------------------------------------------------------------------
# Paths (resolved relative to this test file: repo root -> senzing-bootcamp)
# ---------------------------------------------------------------------------

_REPO_ROOT: Path = Path(__file__).resolve().parent.parent
STEERING_DIR: Path = _REPO_ROOT / "senzing-bootcamp" / "steering"
HOOKS_DIR: Path = _REPO_ROOT / "senzing-bootcamp" / "hooks"

NEXT_STEPS_PATH: Path = STEERING_DIR / "module-completion-next-steps.md"
COMPLETION_PATH: Path = STEERING_DIR / "module-completion.md"
TRANSITIONS_PATH: Path = STEERING_DIR / "module-transitions.md"
CONVERSATION_PROTOCOL_PATH: Path = STEERING_DIR / "conversation-protocol.md"
AGENT_INSTRUCTIONS_PATH: Path = STEERING_DIR / "agent-instructions.md"
ASK_BOOTCAMPER_PATH: Path = HOOKS_DIR / "ask-bootcamper.json"

# Steering ``.md`` files the fix edits or regenerates — excluded from the
# byte-identity baseline. The three edited files change by design; the
# critical-hook registry mirror is regenerated from the edited ask-bootcamper
# prompt by ``sync_hook_registry.py``.
EXCLUDED_STEERING: frozenset[str] = frozenset(
    {
        "module-completion.md",
        "module-completion-next-steps.md",
        "module-transitions.md",
        "hook-registry-critical.md",
    }
)


# ---------------------------------------------------------------------------
# Frozen baseline — computed observation-first from the UNFIXED files.
# After the fix, these detect drift in any non-target file.
# ---------------------------------------------------------------------------

FROZEN_STEERING_SHA256: dict[str, str] = {
    "agent-behavior-rules.md": "31c6580b2bbca2d7e6749e5e0279d124d1970de6b1f03762ad3c5780ada3fd41",
    "agent-context-management.md": "107e2a61943382178938983e08929880576caae97bf531b89f5d9f9bdf117784",
    "agent-instructions.md": "a9d893817df0a313e5a38ca489992e1e738143a9206284491f015aad992a863d",
    "cloud-provider-setup.md": "8231b67aee68c6b50a500f2f8986c3399a002513a86ff540159cb9f61d0053af",
    "common-pitfalls.md": "b32af2368df06740c85ec798d284201f73c823393b37eadc318dd176678de7b3",
    "completion-summary-offer.md": "7c2fef3623cec943c31735ef8e516de26a3d4775cab439f0b1e07104c34222e1",
    "complexity-estimator.md": "9a5dd2e3dee61a673794940fb5f8ebca297047d98c172a56e0f4f6b8f4946fb7",
    "conversation-examples.md": "15535c227fcd3ed4c7784ba299d5c38e83ce1ec30e0dc2c90fc79faeef07eeb4",
    "conversation-protocol.md": "07d601fb19edd15fee172a1bd8fb3a8fb8cf9c5e1c3e5299257571cbd967f99f",
    "data-lineage.md": "fa6d7ffb2414aa29430ce5dfbbd43b0106f67cede39c270c7beaec4349b8ff03",
    "data-processing-reference.md": "e871fd7592bb8258aaf0e3bfd8a56e265453329a61eba2af81726a04614143fd",
    "deployment-aws.md": "5713952ea370808b1f5b03000abdcaad2f248a488c73d3479c8515c3ce19afd9",
    "deployment-azure.md": "6eb62ad60760ba37bc529c9832cbba6b23b9cca88395fddf3011b6fe41616ba3",
    "deployment-gcp.md": "7764d83d647563aad86e789a1ebc451060841a06fb5d329a2cd9faadec0ede90",
    "deployment-kubernetes.md": "468e4b3bedb25e4de4e2c6ec1e0b8b6d61d161288cfb0f9679dcab473dd91437",
    "deployment-onpremises.md": "5702597f302f904e51b67a18e87f661eb2b752fce3860ca1ffcf69d1d19812f8",
    "design-patterns.md": "1a4b6ce219bb524f9548ff39fd7ed32196165ecf9321d5bff72dc66e7dc94de5",
    "entity-resolution-intro.md": "563946c0691714ab7adb4cabf283a69bc09654f88d9cdd2ad34934dd61d928e3",
    "environment-setup.md": "7061faeaedc783eba9416121c41da99d4fd764288cf54420da04ae7c9b7466dd",
    "feedback-workflow.md": "fc0f8a625e026f320e8fd7ab9651f28e08f394a48f54972e98fc435c63fdac18",
    "file-placement.md": "08e13d971f93b24f860c5d824718751d33e7f494e869c8b020ea1ca68b551022",
    "graduation.md": "a55b8add275ed588993b8ae9c1c92f5a1f8a40b1b158102ecfc7d22bc15a4cba",
    "hook-architecture.md": "2548e34453d88f982dd3befe41db1eb5f666bdd8d7c333dcd6d1b618f1765b88",
    "hook-registry-module-01.md": "c72cac28d891570c02c5b5dfd0536d1f31544353cdd1a58c941ff69dbc71a047",
    "hook-registry-module-02.md": "2c08c5a9d54ae1aef6df0a77c3939f9c9165cbb9e87fe93a0f47e90c4b9467c6",
    "hook-registry-module-03.md": "2767780ea5814bfe7b15c007532ad8172cb9f12c9cf015ceeac138256d45b720",
    "hook-registry-module-04.md": "77aedd923850ee4b8bb095d41b6c7fc7a1cb0a0d6f31990c576a3775bb4e4877",
    "hook-registry-module-05.md": "65a1a49ec1f993df938fe8d44db289b7771a974b5eea27ba8985119687dfdde9",
    "hook-registry-module-06.md": "9282637b3de82da1dcb6af83a6d8692c1527ac39d4801076b11c076a833d604b",
    "hook-registry-module-07.md": "c2ddd2dca354ee40cbedb3c2fc2db943a4849f8a389ac3c6f6b5bd06f22f2ee4",
    "hook-registry-module-08.md": "99984f29f77fdf51c2c90cab3560258c3bc29c131a58bd9675e69f8c7cd02276",
    "hook-registry-module-09.md": "71b00ada4b583d4a82d49de9286886c63e71eff5988a6f2339cd42191decabd8",
    "hook-registry-module-10.md": "70e58ecefb078e61d3062e0042bd4bc0cb82ad4c135735d5e7cb3c0e47e59930",
    "hook-registry-module-11.md": "7cbc03a5904d6355899be1eea0ed8c8bdb5ea2e2c35785cd22f7ffaf7453b7ed",
    "hook-registry-module-any.md": "0db6d5def57aa6bb6a87d4d9b9248d9976461a660f0595e52788bdc8e45a45e7",
    "hook-registry.md": "631172b58895e6d43fe1ea0e4a17e095adfe9cba536e059cdd5f973c80564f53",
    "inline-status.md": "a7a5c6410d509cf873a89cbfc327ed6d011931a6798ce9e4eac73c420e25b343",
    "lang-csharp.md": "a180755817e05f2dffc7337207de7587666e090b10c4163f1a14bd205edee9c3",
    "lang-java.md": "31ab2f7771df6ab62b6a0a66e15871d50c6378e40463a91620e462b9513d8bdd",
    "lang-python.md": "15114d9eb719de92aa060649aa8e1bddb8ad01cb6b04a3ff73ca22abb8433a76",
    "lang-rust.md": "293a5297ada2271ae1f9c7f6879e1d59e33beb4b8f4bc23cca53bc91e858a485",
    "lang-typescript.md": "0e4f2b15a5a372ee93493d85cbaca38e8ed636c46ecef5878adb45330b56db31",
    "lessons-learned.md": "e187627da3da25239934c7e162d36a4a2c4099483a0b67871207cd2fbb3c0c4a",
    "mcp-response-caching.md": "0034711066434226c01cf1f21b002d749701e428903c8b1407f37df94f6ef802",
    "mcp-tool-decision-tree.md": "eb62d783cea8dcd3c67cf393077c3cc4c4ac69303afe49defe1734d17ec2378d",
    "mcp-usage-reference.md": "87ef56116c96c57d31578f13c83b03ec7712facbab743fe8580e36f38957768c",
    "module-01-business-problem.md": "1202e796edf5cb45fce00a9050f74c7aa784eb0d351118725ff1dec593e95cce",
    "module-01-phase1-discovery.md": "98087cf29bcd5dad4ac886b330bce3a79f09e2e63c5116e1cae499f22acb8724",
    "module-01-phase2-document-confirm.md": "e14a9b9069b4ab7bd95a55c2865a105d64be02df03e0bfb4c95371489f38dd22",
    "module-02-sdk-setup.md": "9589d1c5a7935100e9460c283a82aa0b8694e32f2cad15318cbe250af8515caf",
    "module-03-phase1-verification.md": "af3595feb0b211410ce462eab76c7a01b9c18860cb277fd44ee8f70661340eda",
    "module-03-phase2-visualization.md": "9bade614f85509f23a111953531aa21c8aaa801da2bf8906cf2361e5fa91c177",
    "module-03-phase3-report-close.md": "7c01c74054b204a66e71b4ef4d053ecf10d0cf457ccaadf8c021494f1b3ba4e4",
    "module-03-system-verification.md": "cb87aaeafb23e1e657ee53b196a52c500cf17bccd5134665fd5c431aa6f7c0e9",
    "module-03-visualization-api-reference.md": "504ad409a3e23190c85b6c08965bd746f6c65016964fa27b2e8244884df3b152",
    "module-04-data-collection.md": "6370b65af37224a039dc5fb50b108cacd84e7417613d4d20ac3cc9b908eeee7a",
    "module-05-data-quality-mapping.md": "c26e4eac1943b0651a577d50787ad2a3fa40d202ac505a33d6ebf7f94ee0b77b",
    "module-05-phase1-quality-assessment.md": "1a5eed83e19124a6691bf24baef1730117af075bde8c7b8dab7bdfa723caa0c6",
    "module-05-phase2-data-mapping.md": "ed622d12e23133f75cde955e7151395d232f33778108b383231d4fd91a78775a",
    "module-05-phase3-test-load.md": "ba5a9456b4d0ac207bb5f6243ca369b5d5843ae4ad6b3de96b9c1d21c0949d7f",
    "module-06-data-processing.md": "80aa187449a55e5ea7b99554bfa4cd864b4bd624b9cb3792e2346e054c0dfb12",
    "module-06-phaseA-build-loading.md": "d6a666b45c15d2621d1cbb2b91ffa0de8e0eef114ec8502fc880b57f83b96192",
    "module-06-phaseB-load-first-source.md": "6699dd2dee8f9ab1c11dfb1ace5ad1c658fb96f7e753c156013583cf28218b93",
    "module-06-phaseC-multi-source.md": "9d6205e7311a6d4a420b7d52deef7755b0a01c0c036b58dbd8931387d33484e8",
    "module-06-phaseD-validation.md": "b030ec0f19a811418081b7fc1102b45f8a7e883676fa3794db25b50dd11fe0ae",
    "module-07-phase1-query-visualize.md": "36e29817caeb46bb7ce66d76500ec7a71d6547de559c1f7792383d5555c9ac9e",
    "module-07-phase2-discover.md": "03bfb645f30c4d68447bacaae451b64152782b55be85e9423af1b9fb06c0e783",
    "module-07-phase2b-discover.md": "43ec75fd2fce2647a76ad4dbd8863ac52e97d6617f37771009c6014226a175f9",
    "module-07-query-visualize-discover.md": "796c7370965844710d815b02a5f3415255e8da7a793624f603ac4ee972a54995",
    "module-08-performance.md": "1cbe3773119ee4e54db33169a2dfe46b078e93dc7f1e68e5e1ae12e27c405bb8",
    "module-08-phaseA-requirements.md": "f6c5c19aeeacb58feda2271ec8000e5876c1364662a725bc6a4551fc017322e6",
    "module-08-phaseB-benchmarking.md": "4160f4adde30c87c1d13c204096fcf551d07905a02f10b87db085a9f6c21887e",
    "module-08-phaseC-optimization.md": "d91c1b3e2fb313d6e5df549135e5f624dc951a92da85ce73ca1c05346cf30b07",
    "module-09-phaseA-assessment.md": "53519c2f1598fcf2f2892750e1f617e2174a6d851e4f23364460165f780318c3",
    "module-09-phaseB-hardening.md": "8ee7d7051db0ee4d597a761e15d228356ec00610cc64bb953717015579bd7d31",
    "module-09-security.md": "38afb9f301de5efe6bdcb0577d16d803e07adf01763da7077366306c6196f838",
    "module-10-monitoring.md": "2aef0e0405c7f78c51747b40de662f9650667a55480d7c2808be839468135330",
    "module-10-phaseA-setup.md": "b700ea19ec2aae8646a7ed1c04e0ab9d774f7747d21f9335b51761500708361a",
    "module-10-phaseB-operations.md": "52debcbaa6a833959e517a32ab3d3253fdb75012e3c41b1fada44b45a3e71450",
    "module-11-deployment.md": "c2b0cc8726d37fb2bc477b5dc57b62cb98f18a0b08f7044519b7472a9b7a1e57",
    "module-11-phase1-packaging.md": "0955e7267f2369c4a166ac02aac1c84d839c0db7d1b9c40be60e308b94712300",
    "module-11-phase2-deploy.md": "ec8bfe33825b238d842beef8e39fc9e1a0002e9cfe4ea1eb637809f86568491f",
    "module-completion-artifacts.md": "cfa71508cde148576591c678ceb8bc5d76f34bdc5040870eeeb36968a8ac9d0a",
    "module-completion-error-handling.md": "060a8e667a0b3b992a20b6db99d5a673dda1bb67b1d1d56396617089aae994d2",
    "module-completion-track.md": "c55e57b45725e7dd574a1bac57d778eb7ceef689d072ed954b2660909cae13ac",
    "module-prerequisites.md": "7b699eb0a77dade0adde6eae157daa21064a9c9bf63b590c5ef2a7b3f64a2eb7",
    "onboarding-flow.md": "861188e9d5cd29fd7b9b3be262c08930f4d8c5e8b4f2de8bd102fe651b69f18e",
    "onboarding-phase1b-intro-language.md": "1ead8ecd4f17b4c986c8c5db60d7fded48480cdbc0ed733fec1dffe450cc29cf",
    "onboarding-phase2-track-setup.md": "608020f48fb2e251bfb5c97f75cf688a9a9da524eacc8aa96e761cb8dd93b39b",
    "phase-loading-guide.md": "75b05f6a5ac36c4ecce30b4603ede6aacec614c4956dd3062fbe5fb873a29ea9",
    "project-structure.md": "572ff31acf48c38e4763afc9a76307dc114e6c116f600b66c63f2492f6f65f83",
    "qa-transcript.md": "426f19352db735ae4f3a46f828214c672f6f963bf288e8ea368db08b2e79e1e1",
    "recovery-from-mistakes.md": "90265df7ff63634f8fef286f15541134eca56a10b42937dee7443b7a06530c37",
    "security-privacy.md": "8e286ee46c0d38e0c7fcaa7d546ed4ba0e1f1ab11bc1552640464c301fbcd125",
    "session-handoff.md": "dc28fd89b2abc56d04d827201c0a77f8efcdaa25ac76560a1825922b9f488950",
    "session-resume-phase2-mapping.md": "4b65ee076c0c59bc641b8198b4eec6fe7344e36b2ce28842ab3cc8843081c05a",
    "session-resume-phase2-setup-recovery.md": "d4b743beb36ddaa042704ca025353e3c6d4d6af9c55089ab3f0ca33107c1aeed",
    "session-resume-phase2-state-repair.md": "7fa92e8d1dee81f9cc05dd93facaa5c62433ddc6b9fc79825d29e0220eda839a",
    "session-resume.md": "8895b4e0ed2d8cdbb6b666165a3afcd465f92351e2201d9fa81a1db13d7d2975",
    "skip-step-protocol.md": "905b92e1df6bd3efb7b362c1cfde1ea2e3c821074dbcfdc3f6b17a473dd07f69",
    "slash-backup-project.md": "8e76c8751ece497f6afd78b3ee5159ae9efde358c1f70ef1242396b1b9c939de",
    "slash-commonmark-validation.md": "8d317fd9944fb17227e318455d4dd7aedde6543fe848289376f5c4b277e31e2e",
    "slash-git-commit.md": "a980a7565efe2b676f49b943d0c5d8fe5cbce97f21148709eac0768b6c2f66dd",
    "track-switching.md": "8088f5ad8e4e9d014cad6d71b4ed5c287db20fa6e5ce65e843798e9549c66a8d",
    "troubleshooting-commands.md": "67abf2c9212723935ee4088e2793153aaa34095dd51fa7e3980ed835d78dd917",
    "troubleshooting-decision-tree.md": "db7daa3cb89385c64f3e3df6f64ceb6cda92945cb3d2ef266fa92a3f14c80191",
    "uat-framework.md": "b9e9deea8378113bfe2afcee4d8c20ba25a22b08cff52740ebc963f0cc56ec5d",
    "verbosity-control.md": "529e71dd6e9c0dfe17d5e40c9d9fbad76b5b10e47ca34585f05bfb3d910e6b6e",
    "visualization-guide.md": "8bd790ff44d4b535ebe2c11595ee25938d9055cb11dda78f2d641644d209bcc8",
    "visualization-web-service.md": "a72c39a19eec1201a1d376a7826ba4436f483551c8c5f6adaa9cda7a3a9f5213",
    "whats-new.md": "74bd3b4d6a549f2ccf6bfe411c800104802d9eb123c13110a88c478063b4fcc0",
}

# Frozen SHA-256 of the ``ask-bootcamper`` prompt regions the fix must NOT touch
# (Phases 0, 2, 3, 4). Phase 1 and Phase 1.5 are intentionally omitted — they are
# the only regions the fix edits.
FROZEN_HOOK_PHASE_SHA256: dict[str, str] = {
    "phase_0": "a14dfefb89f2a01ea581d6a7764e4a4b773cab3c6f8cb7f167a58c572d3eada1",
    "phase_2": "b2e44fc7eb9bc5716644620a6413532dc883450f6a0962dd9aa16c9ec1c5f46c",
    "phase_3": "7f58f39f2ef3f5f667d3650b030f967179886cfd74554b6fe407fc0bc363c9ea",
    "phase_4": "fd66030325b9ef10f332f9723e8ff688d1536db50f83da806cefc082b497bccd",
}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def sha256_bytes(data: bytes) -> str:
    """Return the hex SHA-256 digest of raw bytes.

    Args:
        data: The bytes to hash.

    Returns:
        The lowercase hex SHA-256 digest.
    """
    return hashlib.sha256(data).hexdigest()


def _read(path: Path) -> str:
    """Return the UTF-8 text of a file."""
    return path.read_text(encoding="utf-8")


def ask_bootcamper_hook() -> dict:
    """Return the first (only) hook entry of the ``ask-bootcamper`` Stop hook."""
    return json.loads(_read(ASK_BOOTCAMPER_PATH))["hooks"][0]


def ask_bootcamper_prompt() -> str:
    """Return the ``action.prompt`` text of the ``ask-bootcamper`` Stop hook."""
    return ask_bootcamper_hook()["action"]["prompt"]


def extract_between(text: str, start: str, end: str) -> str:
    """Return the substring of ``text`` from marker ``start`` up to marker ``end``.

    Both markers must occur exactly once and in order. The returned region
    includes ``start`` and excludes ``end`` — matching the region boundaries
    used to compute the frozen phase hashes.

    Args:
        text: The full text to slice.
        start: A marker that appears exactly once, marking the region start.
        end: A marker that appears exactly once after ``start``, ending it.

    Returns:
        The substring ``text[start_index:end_index]``.

    Raises:
        AssertionError: If either marker is missing, non-unique, or out of order.
    """
    assert text.count(start) == 1, f"start marker not unique ({text.count(start)}): {start!r}"
    assert text.count(end) == 1, f"end marker not unique ({text.count(end)}): {end!r}"
    s = text.index(start)
    e = text.index(end)
    assert s < e, f"markers out of order: {start!r} must precede {end!r}"
    return text[s:e]


def hook_phase_region(name: str) -> str:
    """Return the ``ask-bootcamper`` prompt region for a named non-target phase.

    Args:
        name: One of ``phase_0``, ``phase_2``, ``phase_3``, ``phase_4``.

    Returns:
        The exact prompt substring for that phase, boundary-matched to the
        frozen-hash computation.
    """
    prompt = ask_bootcamper_prompt()
    boundaries = {
        "phase_0": ("PHASE 0: MODULE RECAP APPEND", "PHASE 1: CLOSING QUESTION"),
        "phase_2": ("PHASE 2: STEP SEQUENCING", "PHASE 3: MCP-FIRST COMPLIANCE"),
        "phase_3": ("PHASE 3: MCP-FIRST COMPLIANCE", "PHASE 4: QUESTION FORMAT"),
        "phase_4": ("PHASE 4: QUESTION FORMAT", "OUTPUT RULES"),
    }
    start, end = boundaries[name]
    return extract_between(prompt, start, end)


# ---------------------------------------------------------------------------
# Strategies
# ---------------------------------------------------------------------------


def st_non_target_steering_file() -> st.SearchStrategy[str]:
    """Strategy over the frozen non-target steering file names.

    Returns:
        A ``sampled_from`` strategy yielding the file names in
        :data:`FROZEN_STEERING_SHA256` (every ``.md`` steering file the fix must
        leave byte-identical).
    """
    return st.sampled_from(sorted(FROZEN_STEERING_SHA256))


def st_non_target_hook_phase() -> st.SearchStrategy[str]:
    """Strategy over the non-target ``ask-bootcamper`` phase names.

    Returns:
        A ``sampled_from`` strategy yielding ``phase_0``, ``phase_2``,
        ``phase_3``, ``phase_4`` — the phases the fix must not change.
    """
    return st.sampled_from(sorted(FROZEN_HOOK_PHASE_SHA256))


# ---------------------------------------------------------------------------
# Property 3 — byte-identity of non-target steering files
# ---------------------------------------------------------------------------


class TestNonTargetSteeringFilesByteIdentity:
    """Every non-target steering ``.md`` file stays byte-identical after the fix.

    **Property 3: Preservation — Non-Target Steering Files Unchanged**

    The frozen SHA-256 baseline is compared against the current bytes. The
    property (PBT) samples over the file set; the exhaustive deterministic test
    guarantees full coverage of all files regardless of the active Hypothesis
    example count.

    **Validates: Requirements 3.5, 3.6**
    (other single-👉 paths — onboarding, mid-module, feedback, graduation — and
    the compound-question rewrite rule live in these unchanged files)
    """

    @given(name=st_non_target_steering_file())
    def test_non_target_steering_file_matches_frozen_hash(self, name: str) -> None:
        """A sampled non-target steering file's bytes match the frozen baseline."""
        path = STEERING_DIR / name
        assert path.exists(), f"non-target steering file went missing: {name}"
        actual = sha256_bytes(path.read_bytes())
        assert actual == FROZEN_STEERING_SHA256[name], (
            f"{name} drifted from the frozen baseline: {actual} "
            f"!= {FROZEN_STEERING_SHA256[name]}"
        )

    def test_all_non_target_steering_files_match_frozen_hashes(self) -> None:
        """ALL non-target steering files match their frozen baseline (exhaustive)."""
        drift: list[str] = []
        for name, expected in sorted(FROZEN_STEERING_SHA256.items()):
            path = STEERING_DIR / name
            if not path.exists():
                drift.append(f"{name}: MISSING (expected {expected})")
                continue
            actual = sha256_bytes(path.read_bytes())
            if actual != expected:
                drift.append(f"{name}: {actual} != {expected}")
        assert not drift, "Non-target steering files drifted:\n" + "\n".join(drift)

    def test_non_target_steering_file_set_matches_frozen(self) -> None:
        """The on-disk non-target ``.md`` set equals the frozen baseline set.

        Catches an added or removed steering file that the byte-identity hashes
        alone would miss (a new file has no frozen entry; a deleted one leaves a
        stale entry).
        """
        on_disk = {
            p.name for p in STEERING_DIR.glob("*.md") if p.name not in EXCLUDED_STEERING
        }
        frozen = set(FROZEN_STEERING_SHA256)
        assert on_disk == frozen, (
            f"non-target steering file set changed; "
            f"added={sorted(on_disk - frozen)} removed={sorted(frozen - on_disk)}"
        )

    def test_excluded_files_are_the_only_edited_targets(self) -> None:
        """The excluded set is exactly the fix's edited/regenerated steering ``.md``."""
        assert EXCLUDED_STEERING == frozenset(
            {
                "module-completion.md",
                "module-completion-next-steps.md",
                "module-transitions.md",
                "hook-registry-critical.md",
            }
        )
        for name in EXCLUDED_STEERING:
            assert (STEERING_DIR / name).exists(), f"expected edited target missing: {name}"


# ---------------------------------------------------------------------------
# Property 3 — edited files retain their non-target anchors
# ---------------------------------------------------------------------------


class TestModuleCompletionNonTargetAnchors:
    """`module-completion.md` keeps its non-target completion anchors.

    **Property 3: Preservation** — the fix only adds a render-once clause; the
    fixed completion step order, the Shared Boundary-Detection Trigger rules,
    and the defer-when-pending / no-op rules are unchanged.

    **Validates: Requirements 3.3, 3.4**
    """

    def test_retains_fixed_completion_step_order(self) -> None:
        """The six completion steps appear in their fixed, invariant order."""
        text = _read(COMPLETION_PATH)
        assert "**fixed, invariant order**" in text
        steps = [
            "**progress_update**",
            "**consolidated_append**",
            "**transcript_reconciliation**",
            "**completion_certificate**",
            "**capture_hook_safeguard**",
            "**next_step_options**",
        ]
        positions = [text.find(step) for step in steps]
        for step, pos in zip(steps, positions):
            assert pos != -1, f"completion step anchor missing: {step}"
        assert positions == sorted(positions), (
            f"completion step order changed: {list(zip(steps, positions))}"
        )

    def test_retains_shared_boundary_detection_trigger_rules(self) -> None:
        """The Shared Boundary-Detection Trigger rules remain present."""
        text = _read(COMPLETION_PATH)
        for anchor in (
            "## Shared Boundary-Detection Trigger",
            "**Fire on every new entry.**",
            "**Include the final module of a track.**",
        ):
            assert anchor in text, f"boundary-detection anchor missing: {anchor}"

    def test_retains_defer_and_noop_rules(self) -> None:
        """The defer-when-pending and no-op trigger rules remain present."""
        text = _read(COMPLETION_PATH)
        assert "**Defer when a question is pending.**" in text
        assert "**No-op when nothing new completed.**" in text


class TestModuleCompletionNextStepsNonTargetAnchors:
    """`module-completion-next-steps.md` keeps its non-target anchors.

    **Property 3: Preservation** — the next-step options set (Proceed, Iterate,
    Explore, Undo, Share) and the ⛔ Immediate Execution rule are unchanged.

    **Validates: Requirements 3.1, 3.7**
    """

    def test_retains_all_next_step_options(self) -> None:
        """All five next-step options remain offered."""
        text = _read(NEXT_STEPS_PATH)
        for option in (
            "**Proceed:**",
            "**Iterate:**",
            "**Explore:**",
            "**Undo:**",
            "**Share:**",
        ):
            assert option in text, f"next-step option missing: {option}"

    def test_retains_immediate_execution_rule(self) -> None:
        """The ⛔ Immediate Execution on Affirmative Response rule is unchanged."""
        text = _read(NEXT_STEPS_PATH)
        assert "### ⛔ Immediate Execution on Affirmative Response" in text
        assert (
            "**There are ZERO permitted steps between the affirmative response "
            "and the module startup sequence.**"
        ) in text
        # The affirmative-response startup sequence: banner -> journey map -> Step 1.
        assert "Display the module banner" in text
        assert "Show the journey map" in text
        assert "Begin Step 1" in text


class TestModuleTransitionsNonTargetAnchors:
    """`module-transitions.md` keeps its non-target anchors.

    **Property 3: Preservation** — the Confirmation Response Requirements table
    and the ascending-numeric-order sequencing rule are unchanged.

    **Validates: Requirements 3.1**
    """

    def test_retains_confirmation_response_requirements_table(self) -> None:
        """The Confirmation Response Requirements table remains intact."""
        text = _read(TRANSITIONS_PATH)
        assert "## Confirmation Response Requirements" in text
        assert "| Required Element | Description | Minimum |" in text
        for row in (
            "| Module Start Banner |",
            "| Journey Map |",
            "| Before/After Framing |",
            "| Step Overview |",
            "| Step 1 Introduction |",
        ):
            assert row in text, f"confirmation-requirements row missing: {row}"

    def test_retains_ascending_numeric_order_rule(self) -> None:
        """The ascending-numeric-order default sequencing rule remains present."""
        text = _read(TRANSITIONS_PATH)
        assert "## Numeric-Order-by-Default Sequencing" in text
        assert "**ascending numeric order**" in text


# ---------------------------------------------------------------------------
# Property 3 — ask-bootcamper structural preservation (trigger, type, phases)
# ---------------------------------------------------------------------------


class TestAskBootcamperStructuralPreservation:
    """`ask-bootcamper.json` keeps its non-target structure and phases.

    **Property 3: Preservation** — the ``Stop`` trigger, ``agent`` action type,
    and Phases 0/2/3/4 are unchanged; only Phase 1 / Phase 1.5 wording changes.

    **Validates: Requirements 3.2, 3.4, 3.6**
    """

    def test_stop_trigger_and_agent_action_type_unchanged(self) -> None:
        """The hook keeps its ``Stop`` trigger and ``agent`` action type."""
        hook = ask_bootcamper_hook()
        assert hook["trigger"] == "Stop"
        assert hook["action"]["type"] == "agent"
        assert hook["name"] == "to wait for your answer"

    @given(phase=st_non_target_hook_phase())
    def test_non_target_phase_region_matches_frozen_hash(self, phase: str) -> None:
        """A sampled non-target phase region matches its frozen baseline."""
        actual = sha256_bytes(hook_phase_region(phase).encode("utf-8"))
        assert actual == FROZEN_HOOK_PHASE_SHA256[phase], (
            f"{phase} region drifted: {actual} != {FROZEN_HOOK_PHASE_SHA256[phase]}"
        )

    def test_all_non_target_phase_regions_match_frozen_hashes(self) -> None:
        """Phases 0, 2, 3, 4 are byte-identical to the frozen baseline (exhaustive)."""
        drift: list[str] = []
        for phase, expected in sorted(FROZEN_HOOK_PHASE_SHA256.items()):
            actual = sha256_bytes(hook_phase_region(phase).encode("utf-8"))
            if actual != expected:
                drift.append(f"{phase}: {actual} != {expected}")
        assert not drift, "Non-target ask-bootcamper phases drifted:\n" + "\n".join(drift)

    def test_edited_phase_headers_still_present(self) -> None:
        """The Phase 1 / Phase 1.5 headers (the only edited regions) still exist."""
        prompt = ask_bootcamper_prompt()
        assert "PHASE 1: CLOSING QUESTION" in prompt
        assert "PHASE 1.5: LEADING-QUESTION COUNT AUDIT" in prompt


# ---------------------------------------------------------------------------
# Property 3 — config/.question_pending lifecycle rules referenced & unchanged
# ---------------------------------------------------------------------------


class TestQuestionPendingLifecycleRulesUnchanged:
    """The `config/.question_pending` lifecycle rules remain referenced.

    **Property 3: Preservation** — write-policy-gate validation, the
    treat-as-answer rule, and the delete-and-process rule are unchanged. These
    live in non-target steering files (also covered by byte-identity), asserted
    here explicitly for the lifecycle-preservation requirement.

    **Validates: Requirements 3.4**
    """

    def test_treat_as_answer_rule_referenced(self) -> None:
        """conversation-protocol.md keeps the treat-as-answer rule."""
        text = _read(CONVERSATION_PROTOCOL_PATH)
        assert "**Treat-as-answer rule:**" in text
        assert (
            "treat the bootcamper's message as an answer to that pending question"
            in text
        )

    def test_write_policy_gate_validation_referenced(self) -> None:
        """conversation-protocol.md keeps the write-policy-gate validation rule."""
        text = _read(CONVERSATION_PROTOCOL_PATH)
        assert (
            "The `write-policy-gate` hook validates every question written to "
            "`config/.question_pending`"
        ) in text

    def test_delete_and_process_rule_referenced(self) -> None:
        """agent-instructions.md keeps the delete-and-process rule."""
        text = _read(AGENT_INSTRUCTIONS_PATH)
        assert "**Delete-and-process rule:**" in text
        assert "delete `config/.question_pending`" in text
