"""Property-based tests for bootcamp_analytics.py using Hypothesis.

Feature: bootcamp-completion-analytics
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

from hypothesis import given, settings
from hypothesis import strategies as st

# ---------------------------------------------------------------------------
# Make scripts importable
# ---------------------------------------------------------------------------
_SCRIPTS_DIR = str(Path(__file__).resolve().parent.parent / "scripts")
if _SCRIPTS_DIR not in sys.path:
    sys.path.insert(0, _SCRIPTS_DIR)

from bootcamp_analytics import (
    AnalyticsReport,
    FrictionPoint,
    ModuleMetrics,
    SkipRecord,
    compute_module_metrics,
    detect_friction_points,
    format_json_report,
    format_text_report,
    parse_session_log,
)


# ---------------------------------------------------------------------------
# Hypothesis strategies
# ---------------------------------------------------------------------------


@st.composite
def st_log_entry(draw) -> dict:
    """Generate a valid session log dict.

    Fields: timestamp (ISO 8601), session_id (text), module (1-11),
    step (1-10), event ("turn" or "correction"), duration_seconds (0-600),
    message (text).
    """
    year = draw(st.integers(min_value=2020, max_value=2039))
    month = draw(st.integers(min_value=1, max_value=12))
    day = draw(st.integers(min_value=1, max_value=28))
    hour = draw(st.integers(min_value=0, max_value=23))
    minute = draw(st.integers(min_value=0, max_value=59))
    second = draw(st.integers(min_value=0, max_value=59))
    timestamp = f"{year:04d}-{month:02d}-{day:02d}T{hour:02d}:{minute:02d}:{second:02d}Z"

    session_id = draw(st.text(min_size=1, max_size=20, alphabet=st.characters(
        whitelist_categories=("L", "N"),
    )))
    module = draw(st.integers(min_value=1, max_value=11))
    step = draw(st.integers(min_value=1, max_value=10))
    event = draw(st.sampled_from(("turn", "correction")))
    duration_seconds = draw(st.floats(min_value=0.0, max_value=600.0))
    message = draw(st.text(min_size=0, max_size=100))

    return {
        "timestamp": timestamp,
        "session_id": session_id,
        "module": module,
        "step": step,
        "event": event,
        "duration_seconds": duration_seconds,
        "message": message,
    }


@st.composite
def st_log_entries(draw) -> list[dict]:
    """Generate a list of valid session log entry dicts.

    Produces between 0 and 50 entries using the st_log_entry strategy.
    """
    return draw(st.lists(st_log_entry(), min_size=0, max_size=50))


@st.composite
def st_skip_record(draw) -> SkipRecord:
    """Generate a valid SkipRecord instance.

    Fields: module_step like "N.M" (module 1-11, step 1-10),
    reason in ("a", "b", "c"), note (text), skipped_at (ISO 8601).
    """
    module = draw(st.integers(min_value=1, max_value=11))
    step = draw(st.integers(min_value=1, max_value=10))
    module_step = f"{module}.{step}"

    reason = draw(st.sampled_from(("a", "b", "c")))
    note = draw(st.text(min_size=0, max_size=100))

    year = draw(st.integers(min_value=2020, max_value=2039))
    month = draw(st.integers(min_value=1, max_value=12))
    day = draw(st.integers(min_value=1, max_value=28))
    hour = draw(st.integers(min_value=0, max_value=23))
    minute = draw(st.integers(min_value=0, max_value=59))
    second = draw(st.integers(min_value=0, max_value=59))
    skipped_at = f"{year:04d}-{month:02d}-{day:02d}T{hour:02d}:{minute:02d}:{second:02d}Z"

    return SkipRecord(
        module_step=module_step,
        reason=reason,
        note=note,
        skipped_at=skipped_at,
    )


# ---------------------------------------------------------------------------
# Property test classes
# ---------------------------------------------------------------------------


class TestComputeModuleMetricsProperties:
    """Property-based tests for compute_module_metrics.

    **Validates: Requirements 2, 10**
    """

    @given(st_log_entries())
    @settings(max_examples=10)
    def test_total_turns_equals_input_entry_count(
        self, entries: list[dict]
    ) -> None:
        """Sum of turn_count across all ModuleMetrics equals input entry count.

        Since all entries generated by st_log_entries have a valid integer
        module field, every entry is counted as a turn in exactly one module.
        """
        metrics = compute_module_metrics(entries)
        total_turns = sum(m.turn_count for m in metrics)
        assert total_turns == len(entries)


class TestDetectFrictionPointsProperties:
    """Property-based tests for detect_friction_points.

    **Validates: Requirements 3, 10**
    """

    VALID_CATEGORIES = {"slow", "high_corrections", "skipped", "mcp_failures"}
    VALID_SEVERITIES = {"high", "medium", "low"}

    @given(st_log_entries(), st.lists(st_skip_record(), min_size=0, max_size=10))
    @settings(max_examples=10)
    def test_returns_only_valid_categories_and_severities(
        self, entries: list[dict], skips: list[SkipRecord]
    ) -> None:
        """All FrictionPoints have valid category and severity values.

        For any generated log entries and skip records, every FrictionPoint
        returned by detect_friction_points must have:
        - category in {"slow", "high_corrections", "skipped", "mcp_failures"}
        - severity in {"high", "medium", "low"}
        """
        metrics = compute_module_metrics(entries)
        friction_points = detect_friction_points(metrics, skips)

        for fp in friction_points:
            assert fp.category in self.VALID_CATEGORIES, (
                f"Invalid category: {fp.category!r}"
            )
            assert fp.severity in self.VALID_SEVERITIES, (
                f"Invalid severity: {fp.severity!r}"
            )


class TestFormatJsonReportProperties:
    """Property-based tests for format_json_report.

    **Validates: Requirements 4, 10**
    """

    @given(st_log_entries(), st.lists(st_skip_record(), min_size=0, max_size=10))
    @settings(max_examples=10)
    def test_format_json_report_always_produces_valid_json(
        self, entries: list[dict], skips: list[SkipRecord]
    ) -> None:
        """format_json_report always produces valid JSON for any AnalyticsReport.

        For any generated log entries and skip records, building an
        AnalyticsReport and calling format_json_report always produces output
        that json.loads can parse without raising.
        """
        metrics = compute_module_metrics(entries)
        friction_points = detect_friction_points(metrics, skips)

        report = AnalyticsReport(
            module_metrics=metrics,
            friction_points=friction_points,
            skipped_steps=skips,
            total_time_seconds=sum(m.total_seconds for m in metrics),
            total_turns=sum(m.turn_count for m in metrics),
            total_corrections=sum(m.correction_count for m in metrics),
            baseline_comparison=None,
        )

        result = format_json_report(report)
        parsed = json.loads(result)
        assert isinstance(parsed, dict)


class TestParseSessionLogProperties:
    """Property-based tests for parse_session_log.

    **Validates: Requirements 1, 5, 10**
    """

    @given(st.text(max_size=1000))
    @settings(max_examples=10)
    def test_parse_session_log_never_raises_on_arbitrary_content(
        self, content: str
    ) -> None:
        """parse_session_log never raises on arbitrary file content.

        For any arbitrary text content written to a file, parse_session_log
        always returns a list gracefully without raising an exception.
        """
        import tempfile
        import os

        fd, tmp_path = tempfile.mkstemp(suffix=".jsonl")
        try:
            with os.fdopen(fd, "w", encoding="utf-8") as fh:
                fh.write(content)
            result = parse_session_log(tmp_path)
            assert isinstance(result, list)
        finally:
            os.unlink(tmp_path)
