#!/usr/bin/env python3
"""Organize mapping workflow output files into project subdirectories.

Routes files generated by the mapping_workflow MCP tool from a flat source
directory into the correct project subdirectories based on file extension.

Usage:
    python3 organize_mapping_files.py --source <dir> --project-root <dir>
    python3 organize_mapping_files.py --dry-run
"""

from __future__ import annotations

import argparse
import shutil
import sys
from dataclasses import dataclass
from pathlib import Path


# ---------------------------------------------------------------------------
# Routing table: extension → target subdirectory (relative to project root)
# ---------------------------------------------------------------------------

ROUTING_RULES: dict[str, str] = {
    ".py": "scripts",
    ".md": "docs",
    ".jsonl": "data",
    ".json": "config",
}


# ---------------------------------------------------------------------------
# Data model
# ---------------------------------------------------------------------------


@dataclass
class MoveResult:
    """Result of attempting to move a single file.

    Attributes:
        source: Original file path.
        destination: Target file path (where it would be or was moved).
        status: One of "moved", "skipped", "unrouted".
        reason: Human-readable explanation (empty for "moved").
    """

    source: Path
    destination: Path | None
    status: str
    reason: str


# ---------------------------------------------------------------------------
# Core logic
# ---------------------------------------------------------------------------


def scan_source(source_dir: Path) -> list[Path]:
    """List regular non-hidden files in a source directory.

    Args:
        source_dir: Directory to scan for files.

    Returns:
        List of paths to regular files (excludes directories and hidden files).
    """
    return [
        entry
        for entry in source_dir.iterdir()
        if entry.is_file() and not entry.name.startswith(".")
    ]


def plan_moves(files: list[Path], project_root: Path) -> list[MoveResult]:
    """Apply routing rules to a list of files and detect conflicts.

    For each file, determines the target subdirectory based on extension.
    If the destination already exists, the file is marked as skipped.
    If no routing rule matches, the file is marked as unrouted.

    Args:
        files: List of file paths to route.
        project_root: Base directory for target subdirectory resolution.

    Returns:
        List of MoveResult objects describing the planned action for each file.
    """
    results: list[MoveResult] = []
    for file in files:
        ext = file.suffix.lower()
        target_subdir = ROUTING_RULES.get(ext)
        if target_subdir is None:
            results.append(MoveResult(
                source=file,
                destination=None,
                status="unrouted",
                reason="no routing rule for extension",
            ))
        else:
            destination = project_root / target_subdir / file.name
            if destination.exists():
                results.append(MoveResult(
                    source=file,
                    destination=destination,
                    status="skipped",
                    reason="file already exists at destination",
                ))
            else:
                results.append(MoveResult(
                    source=file,
                    destination=destination,
                    status="moved",
                    reason="",
                ))
    return results


def execute_moves(plan: list[MoveResult]) -> None:
    """Create target directories and move files according to the plan.

    Only processes entries with status="moved". Creates parent directories
    as needed and moves files using shutil.move.

    Args:
        plan: List of MoveResult objects from plan_moves.
    """
    for result in plan:
        if result.status == "moved" and result.destination is not None:
            result.destination.parent.mkdir(parents=True, exist_ok=True)
            shutil.move(str(result.source), str(result.destination))


def print_summary(plan: list[MoveResult], dry_run: bool) -> None:
    """Print a summary of the organization results.

    Moved/planned moves go to stdout. Skipped and unrouted notices go to stderr.

    Args:
        plan: List of MoveResult objects describing what happened.
        dry_run: Whether this was a dry-run (no files actually moved).
    """
    moved = [r for r in plan if r.status == "moved"]
    skipped = [r for r in plan if r.status == "skipped"]
    unrouted = [r for r in plan if r.status == "unrouted"]

    if dry_run:
        for r in moved:
            print(f"Would move: {r.source.name} \u2192 {r.destination}")
    elif moved:
        for r in moved:
            print(f"Moved: {r.source.name} \u2192 {r.destination}")
    else:
        print("No files required organization.")

    for r in skipped:
        print(f"Skipped: {r.source.name} ({r.reason})", file=sys.stderr)

    for r in unrouted:
        print(f"Warning: {r.source.name} ({r.reason})", file=sys.stderr)


def main(argv: list[str] | None = None) -> int:
    """Parse CLI arguments and orchestrate the file organization workflow.

    Args:
        argv: Command-line arguments (defaults to sys.argv[1:] when None).

    Returns:
        Exit code: 0 on success, 1 on fatal error.
    """
    parser = argparse.ArgumentParser(
        description="Organize mapping workflow output files into project subdirectories.",
    )
    parser.add_argument(
        "--source",
        default=".",
        help="Source directory to scan (default: cwd)",
    )
    parser.add_argument(
        "--project-root",
        default=".",
        help="Project root for target directory resolution (default: cwd)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print planned moves without modifying the file system",
    )

    args = parser.parse_args(argv)

    source = Path(args.source).resolve()
    project_root = Path(args.project_root).resolve()

    if not source.exists() or not source.is_dir():
        print(f"Error: source directory does not exist or is not a directory: {source}",
              file=sys.stderr)
        return 1

    files = scan_source(source)
    plan = plan_moves(files, project_root)

    if not args.dry_run:
        execute_moves(plan)

    print_summary(plan, args.dry_run)
    return 0


if __name__ == "__main__":
    sys.exit(main())
