#!/usr/bin/env python3
"""Organize mapping workflow output files into project subdirectories.

Routes files generated by the mapping_workflow MCP tool from a flat source
directory into the correct project subdirectories based on file extension.

Usage:
    python3 organize_mapping_files.py --source <dir> --project-root <dir>
    python3 organize_mapping_files.py --dry-run
"""

from __future__ import annotations

import argparse
import shutil
import sys
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path

# ---------------------------------------------------------------------------
# Routing model
# ---------------------------------------------------------------------------
#
# Routing is filename-aware and evaluated first-match-wins via ``route()`` over
# the ordered ``ROUTING_RULE_LIST`` below. Each rule pairs a matcher (built with
# the ``match_name`` / ``match_suffix`` / ``match_ext`` factories) with a single
# target subdirectory (a POSIX-style relative path, possibly nested such as
# ``src/mapping`` or ``docs/reference``).
#
# ``ROUTING_RULES`` is retained as an extension -> subdir compatibility table so
# existing callers/tests that introspect extension-level defaults keep working.
# It mirrors the extension-only rules in ``ROUTING_RULE_LIST`` and is NOT the
# routing source of truth -- ``route()`` is.

Matcher = Callable[[str], bool]


def match_name(name: str) -> Matcher:
    """Build a matcher that matches an exact filename.

    Args:
        name: The exact filename to match (e.g. "senzing_entity_specification.md").

    Returns:
        A predicate returning True when the filename equals ``name``.
    """
    return lambda filename: filename == name


def match_suffix(suffix: str) -> Matcher:
    """Build a matcher that matches filenames ending with a suffix.

    Args:
        suffix: The filename suffix to match (e.g. "_mapper.md").

    Returns:
        A predicate returning True when the filename ends with ``suffix``.
    """
    return lambda filename: filename.endswith(suffix)


def match_ext(ext: str) -> Matcher:
    """Build a matcher that matches filenames by extension (case-insensitive).

    Args:
        ext: The file extension to match, including the dot (e.g. ".py").

    Returns:
        A predicate returning True when the filename's suffix equals ``ext``.
    """
    return lambda filename: Path(filename).suffix.lower() == ext.lower()


@dataclass(frozen=True)
class RoutingRule:
    """A single routing rule pairing a filename matcher with a target subdir.

    Attributes:
        matcher: Predicate that tests whether a filename matches this rule.
        target_subdir: POSIX-style relative subdirectory to route matches into.
    """

    matcher: Matcher
    target_subdir: str


# Ordered, first-match-wins. Filename-specific rules precede extension rules so
# that, e.g., ``senzing_entity_specification.md`` and ``*_mapper.md`` are routed
# to their dedicated subdirectories before the generic ``.md`` rule applies.
ROUTING_RULE_LIST: list[RoutingRule] = [
    RoutingRule(match_name("senzing_entity_specification.md"), "docs/reference"),
    RoutingRule(match_suffix("_mapper.md"), "docs/mapping"),
    RoutingRule(match_ext(".md"), "docs/mapping"),
    RoutingRule(match_ext(".py"), "src/mapping"),
    RoutingRule(match_ext(".jsonl"), "data"),
    RoutingRule(match_ext(".json"), "config"),
]

# Extension -> subdir compatibility table (see module note above). Kept in sync
# with the extension-level entries in ROUTING_RULE_LIST. ``.jsonl`` and ``.json``
# destinations are unchanged from prior behavior.
ROUTING_RULES: dict[str, str] = {
    ".py": "src/mapping",
    ".md": "docs/mapping",
    ".jsonl": "data",
    ".json": "config",
}


# Canonical single-copy artifacts: when the routed destination already exists,
# the misplaced source copy is removed (deduplicated) rather than skipped, so
# exactly one copy remains at the conventional location. Scoped narrowly to
# named files so deduplication can never delete bootcamper data or
# correctly-placed files.
CANONICAL_DEDUP_FILES: set[str] = {"senzing_entity_specification.md"}


def route(filename: str) -> str | None:
    """Route a filename to its conventional target subdirectory.

    Evaluates ``ROUTING_RULE_LIST`` first-match-wins. Filename-specific rules
    (exact name, suffix) take precedence over extension rules.

    Args:
        filename: The base file name to route (e.g. "playpalace_mapper.md").

    Returns:
        The POSIX-style relative target subdirectory (e.g. "docs/mapping"), or
        None when no rule matches (the file is left in place and warned about).
    """
    for rule in ROUTING_RULE_LIST:
        if rule.matcher(filename):
            return rule.target_subdir
    return None


# ---------------------------------------------------------------------------
# Data model
# ---------------------------------------------------------------------------


@dataclass
class MoveResult:
    """Result of attempting to move a single file.

    Attributes:
        source: Original file path.
        destination: Target file path (where it would be or was moved).
        status: One of "moved", "skipped", "deduplicate", "unrouted".
            "deduplicate" marks a canonical single-copy artifact (see
            CANONICAL_DEDUP_FILES) whose routed destination already exists; the
            misplaced source copy is removed so exactly one copy remains.
        reason: Human-readable explanation (empty for "moved").
    """

    source: Path
    destination: Path | None
    status: str
    reason: str


# ---------------------------------------------------------------------------
# Core logic
# ---------------------------------------------------------------------------


def scan_source(source_dir: Path) -> list[Path]:
    """List regular non-hidden files in a source directory.

    Args:
        source_dir: Directory to scan for files.

    Returns:
        List of paths to regular files (excludes directories and hidden files).
    """
    return [
        entry
        for entry in source_dir.iterdir()
        if entry.is_file() and not entry.name.startswith(".")
    ]


def plan_moves(files: list[Path], project_root: Path) -> list[MoveResult]:
    """Apply routing rules to a list of files and detect conflicts.

    For each file, determines the target subdirectory via ``route()`` (a
    filename-aware, first-match-wins evaluation). If the destination already
    exists, the file is marked as skipped -- unless it is a canonical
    single-copy artifact (see CANONICAL_DEDUP_FILES), in which case it is marked
    as deduplicate so the misplaced source copy can be removed. If no routing
    rule matches, the file is marked as unrouted.

    Args:
        files: List of file paths to route.
        project_root: Base directory for target subdirectory resolution.

    Returns:
        List of MoveResult objects describing the planned action for each file.
    """
    results: list[MoveResult] = []
    for file in files:
        target_subdir = route(file.name)
        if target_subdir is None:
            results.append(MoveResult(
                source=file,
                destination=None,
                status="unrouted",
                reason="no routing rule for extension",
            ))
        else:
            destination = project_root / target_subdir / file.name
            if destination.exists():
                if file.name in CANONICAL_DEDUP_FILES:
                    results.append(MoveResult(
                        source=file,
                        destination=destination,
                        status="deduplicate",
                        reason="canonical copy already exists; removing misplaced source",
                    ))
                else:
                    results.append(MoveResult(
                        source=file,
                        destination=destination,
                        status="skipped",
                        reason="file already exists at destination",
                    ))
            else:
                results.append(MoveResult(
                    source=file,
                    destination=destination,
                    status="moved",
                    reason="",
                ))
    return results


def execute_moves(plan: list[MoveResult]) -> None:
    """Create target directories and move files according to the plan.

    Processes entries with status="moved" by creating parent directories as
    needed and moving files with shutil.move. Processes entries with
    status="deduplicate" by removing the misplaced source copy ONLY after
    confirming the canonical destination exists, leaving exactly one copy at the
    conventional location. No other status causes any deletion.

    Args:
        plan: List of MoveResult objects from plan_moves.
    """
    for result in plan:
        if result.status == "moved" and result.destination is not None:
            result.destination.parent.mkdir(parents=True, exist_ok=True)
            shutil.move(str(result.source), str(result.destination))
        elif result.status == "deduplicate" and result.destination is not None:
            if result.destination.exists():
                result.source.unlink()


def print_summary(plan: list[MoveResult], dry_run: bool) -> None:
    """Print a summary of the organization results.

    Moved/planned moves go to stdout. Skipped and unrouted notices go to stderr.

    Args:
        plan: List of MoveResult objects describing what happened.
        dry_run: Whether this was a dry-run (no files actually moved).
    """
    moved = [r for r in plan if r.status == "moved"]
    skipped = [r for r in plan if r.status == "skipped"]
    deduplicated = [r for r in plan if r.status == "deduplicate"]
    unrouted = [r for r in plan if r.status == "unrouted"]

    if dry_run:
        for r in moved:
            print(f"Would move: {r.source.name} \u2192 {r.destination}")
    elif moved:
        for r in moved:
            print(f"Moved: {r.source.name} \u2192 {r.destination}")
    else:
        print("No files required organization.")

    for r in skipped:
        print(f"Skipped: {r.source.name} ({r.reason})", file=sys.stderr)

    for r in deduplicated:
        if dry_run:
            print(f"Would deduplicate: {r.source.name} ({r.reason})", file=sys.stderr)
        else:
            print(f"Deduplicated: {r.source.name} ({r.reason})", file=sys.stderr)

    for r in unrouted:
        print(f"Warning: {r.source.name} ({r.reason})", file=sys.stderr)


def main(argv: list[str] | None = None) -> int:
    """Parse CLI arguments and orchestrate the file organization workflow.

    Args:
        argv: Command-line arguments (defaults to sys.argv[1:] when None).

    Returns:
        Exit code: 0 on success, 1 on fatal error.
    """
    parser = argparse.ArgumentParser(
        description="Organize mapping workflow output files into project subdirectories.",
    )
    parser.add_argument(
        "--source",
        default=".",
        help="Source directory to scan (default: cwd)",
    )
    parser.add_argument(
        "--project-root",
        default=".",
        help="Project root for target directory resolution (default: cwd)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print planned moves without modifying the file system",
    )

    args = parser.parse_args(argv)

    source = Path(args.source).resolve()
    project_root = Path(args.project_root).resolve()

    if not source.exists() or not source.is_dir():
        print(f"Error: source directory does not exist or is not a directory: {source}",
              file=sys.stderr)
        return 1

    files = scan_source(source)
    plan = plan_moves(files, project_root)

    if not args.dry_run:
        execute_moves(plan)

    print_summary(plan, args.dry_run)
    return 0


if __name__ == "__main__":
    sys.exit(main())
