#!/usr/bin/env python3
"""Minimal TruthSet-backed standalone visualization generator.

This is the *standalone demo* for the journey-level first-visualization
guarantee (see spec ``module3-first-visualization-guarantee``). It is offered
at the Module 3 Phase 1 Opt-Out Gate when the bootcamper skips verification and
therefore never reaches the Module 3 Step 9 "wow moment".

It reuses the Module 3 Step 9 web-service pattern and constraints from
``senzing-bootcamp/steering/module-03-phase2-visualization.md``:

- Single self-contained HTML file with embedded CSS + JavaScript.
- D3.js v7 loaded from the d3js.org CDN (``d3js.org/d3.v7.min.js``);
  no other external JavaScript dependencies.
- Generated by this ``write_html.py`` script (HTML held as a triple-quoted
  string), never by direct file writes of HTML+JS content.
- All artifacts live inside the working directory
  (``src/system_verification/web_service/``).
- Served by a stdlib HTTP server (see ``server.py``).

Because the opt-out path means no SDK data was loaded, the demo embeds a small
static TruthSet-backed sample (CUSTOMERS, REFERENCE, WATCHLIST) so the
bootcamper still sees entity resolution visualized. "Minimal" means a single
entity-graph view rather than the full Step 9 four-tab dashboard; the pattern
and constraints are identical.

On successful generation this calls
``clear_first_visualization_owed(satisfied_by="standalone_demo")`` so the owed
marker is satisfied. If generation fails, the marker is left ``owed`` so the
deferred guarantee (Module 6/7) still applies.

Usage:
    python3 src/system_verification/web_service/write_html.py
    python3 src/system_verification/web_service/write_html.py --output index.html
    python3 src/system_verification/web_service/write_html.py --no-clear-marker
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

# D3.js v7 from the d3js.org CDN — the only allowed external JavaScript source.
D3_CDN_URL = "https://" + "d3js.org/d3.v7.min.js"

# Node colours by primary data source (matches Step 9 constraints).
SOURCE_COLORS: dict[str, str] = {
    "CUSTOMERS": "#3b82f6",
    "REFERENCE": "#22c55e",
    "WATCHLIST": "#f59e0b",
}


def build_truthset_graph() -> dict:
    """Return a minimal TruthSet-backed graph (nodes + edges).

    The sample spans the three TruthSet data sources (CUSTOMERS, REFERENCE,
    WATCHLIST) and includes multi-record and cross-source entities plus a few
    relationships so the force-directed graph demonstrates entity resolution.

    Edges are keyed by ``source_entity_id`` / ``target_entity_id`` (the Step 9
    ``/api/graph`` contract); the client maps these to ``source`` / ``target``
    before handing them to D3's ``forceLink``.

    Returns:
        A dict with ``metadata``, ``nodes`` and ``edges`` keys.
    """
    nodes = [
        {
            "entity_id": 1,
            "entity_name": "Robert Smith",
            "record_count": 3,
            "data_sources": ["CUSTOMERS", "REFERENCE"],
            "primary_data_source": "CUSTOMERS",
            "records": [
                {"data_source": "CUSTOMERS", "record_id": "1001"},
                {"data_source": "CUSTOMERS", "record_id": "1042"},
                {"data_source": "REFERENCE", "record_id": "R-88"},
            ],
        },
        {
            "entity_id": 2,
            "entity_name": "Jie Wang",
            "record_count": 2,
            "data_sources": ["CUSTOMERS", "WATCHLIST"],
            "primary_data_source": "WATCHLIST",
            "records": [
                {"data_source": "CUSTOMERS", "record_id": "1077"},
                {"data_source": "WATCHLIST", "record_id": "W-14"},
            ],
        },
        {
            "entity_id": 3,
            "entity_name": "Maria Garcia",
            "record_count": 2,
            "data_sources": ["CUSTOMERS", "REFERENCE"],
            "primary_data_source": "REFERENCE",
            "records": [
                {"data_source": "CUSTOMERS", "record_id": "1103"},
                {"data_source": "REFERENCE", "record_id": "R-52"},
            ],
        },
        {
            "entity_id": 4,
            "entity_name": "Robert B. Smith",
            "record_count": 1,
            "data_sources": ["WATCHLIST"],
            "primary_data_source": "WATCHLIST",
            "records": [
                {"data_source": "WATCHLIST", "record_id": "W-07"},
            ],
        },
        {
            "entity_id": 5,
            "entity_name": "Acme Holdings LLC",
            "record_count": 1,
            "data_sources": ["CUSTOMERS"],
            "primary_data_source": "CUSTOMERS",
            "records": [
                {"data_source": "CUSTOMERS", "record_id": "1200"},
            ],
        },
    ]

    edges = [
        {
            "source_entity_id": 1,
            "target_entity_id": 4,
            "match_key": "+NAME+DOB",
            "relationship_type": "possible_match",
        },
        {
            "source_entity_id": 2,
            "target_entity_id": 4,
            "match_key": "+ADDRESS",
            "relationship_type": "discovered",
        },
        {
            "source_entity_id": 3,
            "target_entity_id": 5,
            "match_key": "+ADDRESS+PHONE",
            "relationship_type": "disclosed",
        },
    ]

    records_total = sum(n["record_count"] for n in nodes)
    multi_record = sum(1 for n in nodes if n["record_count"] > 1)
    cross_source = sum(1 for n in nodes if len(n["data_sources"]) > 1)

    return {
        "metadata": {
            "title": "TruthSet Standalone Demo",
            "data_sources": ["CUSTOMERS", "REFERENCE", "WATCHLIST"],
            "records_total": records_total,
            "entities_total": len(nodes),
            "multi_record_entities": multi_record,
            "cross_source_entities": cross_source,
            "relationships_total": len(edges),
        },
        "nodes": nodes,
        "edges": edges,
    }


# The complete single-page visualization. D3.js v7 is loaded from the CDN; the
# graph data is injected at the {{GRAPH_DATA_JSON}} placeholder. Per the Step 9
# D3 code-style constraints: function(){} callbacks (never arrow functions),
# explicit width/height on the SVG, and edges mapped to source/target from
# source_entity_id/target_entity_id before forceLink.
_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Senzing TruthSet Standalone Demo</title>
<script src="__D3_CDN_URL__"></script>
<style>
  * { box-sizing: border-box; }
  body {
    margin: 0;
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
    color: #1f2937;
    background: #f9fafb;
  }
  header {
    height: 50px;
    display: flex;
    align-items: center;
    padding: 0 16px;
    background: #111827;
    color: #f9fafb;
    font-weight: 600;
  }
  #summary-banner {
    display: flex;
    gap: 12px;
    padding: 8px 16px;
    background: #ffffff;
    border-bottom: 1px solid #e5e7eb;
    flex-wrap: wrap;
  }
  .stat {
    display: flex;
    flex-direction: column;
  }
  .stat .value { font-size: 20px; font-weight: 700; }
  .stat .label { font-size: 11px; color: #6b7280; text-transform: uppercase; }
  #graph-container {
    position: relative;
    height: calc(100vh - 120px);
    width: 100%;
  }
  #legend {
    position: absolute;
    top: 12px;
    right: 12px;
    background: rgba(255, 255, 255, 0.95);
    border: 1px solid #e5e7eb;
    border-radius: 6px;
    padding: 8px 10px;
    font-size: 12px;
  }
  #legend .row { display: flex; align-items: center; gap: 6px; margin: 2px 0; }
  #legend .swatch { width: 12px; height: 12px; border-radius: 50%; }
  .node-label { font-size: 11px; fill: #374151; pointer-events: none; }
  .edge-label { font-size: 10px; fill: #6b7280; pointer-events: none; }
  .link { stroke: #9ca3af; stroke-width: 1.5px; }
  #modal-overlay {
    display: none;
    position: fixed;
    inset: 0;
    background: rgba(0, 0, 0, 0.4);
    align-items: center;
    justify-content: center;
  }
  #modal {
    background: #ffffff;
    border-radius: 8px;
    padding: 20px;
    min-width: 300px;
    max-width: 90vw;
    box-shadow: 0 10px 30px rgba(0, 0, 0, 0.2);
  }
  #modal h2 { margin-top: 0; }
  #modal button {
    margin-top: 12px;
    padding: 6px 12px;
    border: none;
    border-radius: 4px;
    background: #111827;
    color: #fff;
    cursor: pointer;
  }
</style>
</head>
<body>
<header>Senzing Entity Resolution — TruthSet Standalone Demo</header>
<div id="summary-banner"></div>
<div id="graph-container">
  <div id="legend"></div>
</div>
<div id="modal-overlay">
  <div id="modal">
    <h2 id="modal-title"></h2>
    <div id="modal-body"></div>
    <button id="modal-close">Close</button>
  </div>
</div>
<script>
var GRAPH_DATA = {{GRAPH_DATA_JSON}};

var SOURCE_COLORS = {
  "CUSTOMERS": "#3b82f6",
  "REFERENCE": "#22c55e",
  "WATCHLIST": "#f59e0b"
};

function nodeRadius(recordCount) {
  return Math.min(Math.max(8 + recordCount * 4, 8), 40);
}

function renderBanner() {
  var m = GRAPH_DATA.metadata;
  var stats = [
    ["Records Loaded", m.records_total],
    ["Resolved Entities", m.entities_total],
    ["Multi-Record Entities", m.multi_record_entities],
    ["Cross-Source Matches", m.cross_source_entities],
    ["Relationships Discovered", m.relationships_total]
  ];
  var banner = d3.select("#summary-banner");
  banner.selectAll("div.stat")
    .data(stats)
    .enter()
    .append("div")
    .attr("class", "stat")
    .html(function(d) {
      return "<span class='value'>" + d[1] + "</span>" +
             "<span class='label'>" + d[0] + "</span>";
    });
}

function renderLegend() {
  var legend = d3.select("#legend");
  legend.append("div").style("font-weight", "600").text("Data Sources");
  Object.keys(SOURCE_COLORS).forEach(function(source) {
    var row = legend.append("div").attr("class", "row");
    row.append("span")
      .attr("class", "swatch")
      .style("background", SOURCE_COLORS[source]);
    row.append("span").text(source);
  });
}

function showModal(node) {
  d3.select("#modal-title").text(node.entity_name);
  var body = "<p><strong>Entity ID:</strong> " + node.entity_id + "</p>" +
             "<p><strong>Data sources:</strong> " + node.data_sources.join(", ") + "</p>" +
             "<p><strong>Record count:</strong> " + node.record_count + "</p>" +
             "<p><strong>Records:</strong></p><ul>";
  node.records.forEach(function(r) {
    body += "<li>" + r.data_source + " / " + r.record_id + "</li>";
  });
  body += "</ul>";
  d3.select("#modal-body").html(body);
  d3.select("#modal-overlay").style("display", "flex");
}

function drawGraph() {
  var container = document.getElementById("graph-container");
  var width = container.clientWidth;
  var height = container.clientHeight;

  var svg = d3.select("#graph-container").append("svg")
    .attr("width", width)
    .attr("height", height);

  var zoomGroup = svg.append("g");

  svg.call(d3.zoom().scaleExtent([0.2, 5]).on("zoom", function(event) {
    zoomGroup.attr("transform", event.transform);
  }));

  var nodes = GRAPH_DATA.nodes.map(function(n) { return Object.assign({}, n); });

  // Map each edge to expose source/target from source_entity_id/target_entity_id
  // BEFORE passing to forceLink (Step 9 Critical Lesson 7 — otherwise the graph
  // renders empty with no console error).
  var links = GRAPH_DATA.edges.map(function(e) {
    return Object.assign({}, e, {
      source: e.source_entity_id,
      target: e.target_entity_id
    });
  });

  var simulation = d3.forceSimulation(nodes)
    .force("link", d3.forceLink(links).id(function(d) { return d.entity_id; }).distance(140))
    .force("charge", d3.forceManyBody().strength(-400))
    .force("center", d3.forceCenter(width / 2, height / 2));

  var link = zoomGroup.append("g").selectAll("line")
    .data(links)
    .enter().append("line")
    .attr("class", "link");

  var edgeLabel = zoomGroup.append("g").selectAll("text")
    .data(links)
    .enter().append("text")
    .attr("class", "edge-label")
    .text(function(d) { return d.match_key; });

  var node = zoomGroup.append("g").selectAll("circle")
    .data(nodes)
    .enter().append("circle")
    .attr("r", function(d) { return nodeRadius(d.record_count); })
    .attr("fill", function(d) { return SOURCE_COLORS[d.primary_data_source] || "#9ca3af"; })
    .attr("stroke", "#ffffff")
    .attr("stroke-width", 1.5)
    .style("cursor", "pointer")
    .on("click", function(event, d) { showModal(d); })
    .call(d3.drag()
      .on("start", function(event, d) {
        if (!event.active) simulation.alphaTarget(0.3).restart();
        d.fx = d.x; d.fy = d.y;
      })
      .on("drag", function(event, d) {
        d.fx = event.x; d.fy = event.y;
      })
      .on("end", function(event, d) {
        if (!event.active) simulation.alphaTarget(0);
        d.fx = null; d.fy = null;
      }));

  var nodeLabel = zoomGroup.append("g").selectAll("text")
    .data(nodes)
    .enter().append("text")
    .attr("class", "node-label")
    .attr("text-anchor", "middle")
    .text(function(d) {
      var name = d.entity_name;
      return name.length > 20 ? name.slice(0, 19) + "\\u2026" : name;
    });

  simulation.on("tick", function() {
    link
      .attr("x1", function(d) { return d.source.x; })
      .attr("y1", function(d) { return d.source.y; })
      .attr("x2", function(d) { return d.target.x; })
      .attr("y2", function(d) { return d.target.y; });

    edgeLabel
      .attr("x", function(d) { return (d.source.x + d.target.x) / 2; })
      .attr("y", function(d) { return (d.source.y + d.target.y) / 2; });

    node
      .attr("cx", function(d) { return d.x; })
      .attr("cy", function(d) { return d.y; });

    nodeLabel
      .attr("x", function(d) { return d.x; })
      .attr("y", function(d) { return d.y + nodeRadius(d.record_count) + 12; });
  });

  window.addEventListener("resize", function() {
    var w = container.clientWidth;
    var h = container.clientHeight;
    svg.attr("width", w).attr("height", h);
    simulation.force("center", d3.forceCenter(w / 2, h / 2));
    simulation.alpha(0.3).restart();
  });
}

d3.select("#modal-close").on("click", function() {
  d3.select("#modal-overlay").style("display", "none");
});
d3.select("#modal-overlay").on("click", function(event) {
  if (event.target.id === "modal-overlay") {
    d3.select("#modal-overlay").style("display", "none");
  }
});

renderBanner();
renderLegend();
drawGraph();
</script>
</body>
</html>
"""


def render_html(graph_data: dict) -> str:
    """Render the self-contained HTML document for *graph_data*.

    Args:
        graph_data: The graph dict from :func:`build_truthset_graph`.

    Returns:
        A complete, self-contained HTML5 document string (D3.js v7 via CDN).
    """
    graph_json = json.dumps(graph_data, separators=(",", ":"))
    html = _HTML_TEMPLATE
    html = html.replace("__D3_CDN_URL__", D3_CDN_URL)
    html = html.replace("{{GRAPH_DATA_JSON}}", graph_json)
    return html


def _clear_owed_marker() -> bool:
    """Best-effort call to ``clear_first_visualization_owed`` on success.

    Imports ``progress_utils`` from ``senzing-bootcamp/scripts`` via ``sys.path``
    (scripts are not packages). Failure to import or clear is non-fatal: the
    demo was still generated, and a stale ``owed`` marker is safely handled by
    the deferred guarantee.

    Returns:
        True if the marker was cleared, False otherwise.
    """
    repo_root = Path(__file__).resolve().parents[3]
    scripts_dir = repo_root / "senzing-bootcamp" / "scripts"
    if str(scripts_dir) not in sys.path:
        sys.path.insert(0, str(scripts_dir))

    try:
        from progress_utils import clear_first_visualization_owed
    except ImportError as exc:
        print(f"Note: could not import progress marker helper ({exc}); marker left unchanged.")
        return False

    progress_path = str(repo_root / "config" / "bootcamp_progress.json")
    try:
        clear_first_visualization_owed(
            satisfied_by="standalone_demo",
            progress_path=progress_path,
        )
    except Exception as exc:  # noqa: BLE001 - marker clearing must never break generation
        print(f"Note: could not clear first-visualization marker ({exc}); marker left owed.")
        return False

    print("Cleared first_visualization marker (satisfied_by=standalone_demo).")
    return True


def build_arg_parser() -> argparse.ArgumentParser:
    """Construct the CLI argument parser."""
    parser = argparse.ArgumentParser(
        description=(
            "Generate the minimal TruthSet-backed standalone demo HTML "
            "(single self-contained file, D3.js v7 CDN)."
        ),
    )
    parser.add_argument(
        "--output",
        default=str(Path(__file__).resolve().parent / "index.html"),
        help="Output path for the generated HTML file (default: ./index.html).",
    )
    parser.add_argument(
        "--no-clear-marker",
        action="store_true",
        help="Do not clear the first_visualization owed marker after generation.",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    """CLI entry-point: generate the standalone demo HTML.

    On successful generation, clears the ``first_visualization`` owed marker
    (unless ``--no-clear-marker`` is given). On failure, returns a non-zero exit
    code and leaves the marker ``owed`` so the deferred guarantee still applies.

    Returns:
        0 on success, 1 on failure.
    """
    parser = build_arg_parser()
    args = parser.parse_args(argv)

    output_path = Path(args.output)
    try:
        graph_data = build_truthset_graph()
        html = render_html(graph_data)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(html, encoding="utf-8")
    except OSError as exc:
        print(f"Error: failed to generate standalone demo: {exc}")
        return 1

    print(f"Generated standalone demo: {output_path}")

    if not args.no_clear_marker:
        _clear_owed_marker()

    return 0


if __name__ == "__main__":
    sys.exit(main())
